name: Yggdrasil
version: "0.4.3-popura1-3"
slug: yggdrasil
stage: experimental
description: Connect to HA remotely via Yggdrasil
url: "https://github.com/averyanalex/ha-addons/tree/main/yggdrasil"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
image: "ghcr.io/averyanalex/ha-yggdrasil-{arch}"
startup: services
host_network: true
devices:
  - /dev/net/tun
privileged:
  - NET_ADMIN
