name: 'HA Build'

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: averyanalex
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Yggdrasil build
      uses: home-assistant/builder@master
      with:
        args: |
          --all \
          --target /data/yggdrasil \
          --docker-hub averyanalex
